# https://github.com/atom/ci
environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: mkdir c:\temp
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off